-- ==============================================================================
-- Migration: Add detailed_description to contenus_oeuvres
-- Purpose: Store a rich, coherent artwork description generated by Gemini
--          from Wikipedia content. This field will progressively replace
--          extended_analysis + historical_context.
-- ==============================================================================

ALTER TABLE public.contenus_oeuvres
ADD COLUMN IF NOT EXISTS detailed_description TEXT NULL;

COMMENT ON COLUMN public.contenus_oeuvres.detailed_description IS
'Rich coherent artwork description (~300-500 words, FR) generated by Gemini from Wikipedia scraping. Cached to avoid re-generation.';
